### PR TITLE
Fix webpack build for crypto & client #492

### LINKED ISSUE #492: Fix webpack build for crypto & client

### PR DESCRIPTION
**Pull request by luciorubeens**
## Proposed changes

Now it will generate two bundles, one for web and another for module bundlers (webpack/rollup/..).
Fixes #492 

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

### CODE REVIEW

File: packages/crypto/lib/managers/config.js [hunk 1]
```diff
@@ -37,6 +37,7 @@ class ConfigManager {
    * Get config from file.
    * @param {String} path
    */
+  // TODO: an warning is generated in the build, should we remove this method?
```
Comment (faustbrian) [inline packages/crypto/lib/managers/config.js]: It is nowhere used, should be fine to be removed.
