### PR TITLE
fix(core-database): assign calculated delegate ranks from temp wallets

### LINKED ISSUE #2350: Delegate ranks in wallet manager are all over the place until the first block is received
**Describe the bug**
When a node is restarted the delegate ranks are all over the place until the first block is received which triggers the recalculation of ranks.

**Note that this does not affect the forging list as the rank property is just returned via API and not used internally.**

**To Reproduce**
The easiest way to visualize this is to run dexplorer locally, use your devnet node as host and keep the delegate monitor open while you restart your node. Shortly after the public API is mounted and new data is polled you will see a delegate list that looks very odd.

This changes a few seconds later as soon as the first block comes in.

**Expected behavior**
Return the correct delegate list right from the start.

### PR DESCRIPTION
**Pull request by supaiku0**
## Summary

Fixes #2350 this time for real.

## What kind of change does this PR introduce?

- [X] Bugfix
- [ ] New feature
- [ ] Refactoring / Performance Improvements
- [ ] Build-related changes
- [ ] Documentation
- [ ] Tests / Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Does this PR release a new version?

- [ ] Yes
  - [ ] All tests are passing
  - [ ] All benchmarks are passing without any _major_ regressions
  - [ ] Sync from 0 works on mainnet
  - [ ] Sync from 0 works on devnet
  - [ ] Starting a new network and forging on it work
  - [ ] Explorer is fully functional
  - [ ] Wallets are fully functional
- [ ] No

## Checklist

- [ ] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation _(if appropriate)_

### CODE REVIEW

File: packages/core-database/src/database-service.ts [hunk 1]
```diff
@@ -632,7 +632,13 @@ export class DatabaseService implements Database.IDatabaseService {
         }
 
         // Now retrieve the active delegate list from the temporary wallet manager.
-        return tempWalletManager.loadActiveDelegateList(roundInfo);
+        const delegates = tempWalletManager.loadActiveDelegateList(roundInfo);
```
Comment (faustbrian) [inline packages/core-database/src/database-service.ts]:
```suggestion
        const delegates: State.IDelegateWallet[] = tempWalletManager.loadActiveDelegateList(roundInfo);
```
