### PR TITLE
fix(core-transactions): do not attempt to convert vendorfield

### LINKED ISSUE #3251: [2.6][T4] vendorfield conversion from buffer to string in htlc transactions
#3213 introduced a bug, i.e. the `vendorField` is converted from Buffer to string in the `applyToSender` and `revertForSender` methods. This conversion is only needed during bootstrap, and otherwise cause a wrong `vendorField` (i.e. empty string) to be inserted into the wallet attributes instead.

To reproduce:

- send htlc lock with vendorfield (e.g. `foobar`)
- visit http://NODE_IP:4003/api/locks/LOCK_ID → vendorField is `""`
- restart node
- visit http://NODE_IP:4003/api/locks/LOCK_ID → vendorField is restored (e.g. `"foobar"`)

### PR DESCRIPTION
**Pull request by dated**
## Summary

Fixes #3251.

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

File: packages/core-transactions/src/handlers/htlc-claim.ts [hunk 1]
```diff
@@ -175,9 +175,7 @@ export class HtlcClaimTransactionHandler extends TransactionHandler {
             amount: lockTransaction.amount,
             recipientId: lockTransaction.recipientId,
             timestamp: lockTransaction.timestamp,
-            vendorField: lockTransaction.vendorField
-                ? Buffer.from(lockTransaction.vendorField, "hex").toString("utf8")
```
Comment (supaiku0) [inline packages/core-transactions/src/handlers/htlc-claim.ts]: This needs to stay, only the HTLC lock is wrong. The reverts get Buffers from the database.
