### PR TITLE
fix(core-api): fix wallet/transactions confirmations and timestamp fields

### LINKED ISSUE #3758: Core v3: API response shows 0 confirmations
`/api/wallets/<wallet address>/transactions` API endpoint shows 0 confirmations for transactions that should be confirmed, which in result makes Desktop Wallet gray out transactions (eg. showing them as "pending") so you cannot use those funds.

**Expected Behavior**

It should show proper number of confirmations.

**Current Behavior**

It shows 0 confirmations for transactions that should be confirmed.

**Steps to Reproduce (for bugs)**

make an API call to` /api/wallets/<wallet address>/transactions` and see the response of transactions it shows 0 for them.

### PR DESCRIPTION
**Pull request by rainydio**
## Summary

Includes #3733 (should be merged first), fixes #3758 and #3759, and [comment] in #3741. All related to search and api.

Similarly to #3733 new set of methods `...joinBlock` are introduced to `TransactionHistoryService`. Joined block data is then used to calculate `confirmations` and `timestamp` in api response.

Implemented `address` criteria that searches by both `senderId` and `recipientId`. Note that it is `address`, not `addresses` which similar to other fields (`recipientId`, not `recipientIds`), but incompatible with v2.6.

## Checklist

- [ ] Tests
- [x] Ready to be merged

[comment]: https://github.com/ArkEcosystem/core/issues/3741#issuecomment-634043543

### CODE REVIEW

File: packages/core-database/src/transaction-filter.ts [hunk 1]
```diff
@@ -32,8 +32,18 @@ export class TransactionFilter implements Contracts.Database.TransactionFilter {
...
+                    return handleOrCriteria(criteria.address!, async (c) => {
+                        return this.handleAddressCriteria(c);
+                    });
                 case "senderId":
-                    return handleOrCriteria(criteria.senderId!, (c) => this.handleSenderIdCriteria(c));
+                    return handleOrCriteria(criteria.senderId!, async (c) => {
+                        return this.handleSenderIdCriteria(c);
+                    });
+                case "recipientId":
+                    return handleOrCriteria(criteria.recipientId!, (c) => {
```
Comment (air1one) [inline packages/core-database/src/transaction-filter.ts:44]:
```suggestion
                    return handleOrCriteria(criteria.recipientId!, async (c) => {
```
